# Generated by Django 3.1.1 on 2020-10-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_actor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Show',
        ),
        migrations.AddField(
            model_name='actor',
            name='shows',
            field=models.ManyToManyField(to='shows.Show'),
        ),
    ]
