# Generated by Django 3.1.1 on 2020-10-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20201029_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='show',
            field=models.ManyToManyField(to='shows.Show'),
        ),
    ]
