# Generated by Django 3.1.1 on 2020-10-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_actor_show'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
