# Generated by Django 3.1.1 on 2020-10-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_actor_show'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
